version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "===> Installing Terraform"
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip
      - unzip -o terraform.zip
      - mkdir -p $HOME/bin
      - mv terraform $HOME/bin/
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
      - export PATH=$HOME/bin:$PATH
      - terraform -version

  pre_build:
    commands:
      - export PATH=$HOME/bin:$PATH
      - echo "===> terraform init"
      - terraform init

      - echo "===> terraform validate"
      - terraform validate

  build:
    commands:
      - export PATH=$HOME/bin:$PATH
      - echo "===> terraform apply"
      - terraform apply -auto-approve \
          -var="codestar_connection_arn=$CODESTAR_CONNECTION_ARN" \
          -var="dockerhub_secret_arn=$DOCKERHUB_SECRET_ARN"
