---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing unzip...
      - yum install -y unzip
      - echo Installing Terraform...
      - curl -O https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip
      - unzip terraform_1.3.9_linux_amd64.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/ || mv terraform /bin/
      - terraform -version

  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform apply -auto-approve \
        -var="codestar_connection_arn=$CODESTAR_CONNECTION_ARN" \
        -var="dockerhub_secret_arn=$DOCKERHUB_SECRET_ARN"
