---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # just to keep AWS CodeBuild happy
    commands:
      - echo "===> Downloading Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip || (echo "Failed to download Terraform" && exit 1)
      
      - echo "===> Unzipping Terraform..."
      - unzip terraform_1.3.9_linux_amd64.zip || (echo "Failed to unzip Terraform" && exit 1)
      
      - echo "===> Moving Terraform binary to /usr/local/bin..."
      - mv terraform /usr/local/bin/ || (echo "Failed to move Terraform binary" && exit 1)
      
      - echo "===> Verifying Terraform installation..."
      - terraform -version || (echo "Terraform not found after install" && exit 1)

  pre_build:
    commands:
      - echo "===> Running terraform init..."
      - terraform init || (echo "Terraform init failed" && exit 1)

      - echo "===> Running terraform validate..."
      - terraform validate || (echo "Terraform validate failed" && exit 1)

  build:
    commands:
      - echo "===> Running terraform apply..."
      - terraform apply -auto-approve \
          -var="codestar_connection_arn=$CODESTAR_CONNECTION_ARN" \
          -var="dockerhub_secret_arn=$DOCKERHUB_SECRET_ARN" || (echo "Terraform apply failed" && exit 1)
