---
version: 0.2

phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform apply -auto-approve \
          -var="codestar_connection_arn=$CODESTAR_CONNECTION_ARN" \
          -var="dockerhub_secret_arn=$DOCKERHUB_SECRET_ARN"
